### ISSUE TITLE
when i just read the example i can't understand how to DIY the colors for me.

### ISSUE THREAD

**Issue by normidar** [Cleveroad/flutter_sliding_tutorial#14]
please set the colors required and add them to the example code, please.

**Comment by NikitaAmelinCR** [comment]
@normidar 
We added [an example of customizing page background colors](https://github.com/Cleveroad/flutter_sliding_tutorial/blob/master/example/lib/sliding_tutorial.dart).
Please use the latest version. 

Thank you for your contribution.
