### ISSUE TITLE
Error on running ios example

### ISSUE THREAD

**Issue by vietstone-ng** [Cleveroad/flutter_sliding_tutorial#21]
When I tried to run the example on iOS Simulator, I encountered the error as the screenshot.
After some research, I can fix with 2 steps below:
- in Podfile, uncomment line 2 (remove the # character, means force build for ios 9 instead of default ios 8)
`platform :ios, '9.0'`
- run `pod install` in `ios` folder

Although I can fix it with these 2 steps, I think this's not the correct change to make a new PR (especially `pod install`). Maybe some changes from Flutter configuration is the right solution.

\<Error screenshot\>
<img width="933" alt="Screen Shot 2022-01-16 at 9 51 57 AM" src="https://user-images.githubusercontent.com/744353/149645817-5906040a-dcfb-49ea-b826-b1f01c481b41.png">

**Comment by NikitaAmelinCR** [comment]
Hi @vietstone-ng! Sorry for delay.  It has been fixed in #22. Thanks!
