### ISSUE TITLE
Sliding indicator imprecision

### ISSUE THREAD

**Issue by SeriousMonk** [Cleveroad/flutter_sliding_tutorial#4]
Hi, the inactiveIndicator and activeIndicator in the SlidingIndicator widget are no properly aligned and it's triggering my OCD. The activeIndicator is slightly offset downwards, creating a tiny gap above the icon.

**Comment by SeriousMonk** [comment]
By setting the activeIndicator's size to 1 unit bigger than the inActiveIndicator's size and changing 
```dart
Offset((margin * 2 + sizeIndicator) * correctScroll, 0)
```
to
```dart
Offset((margin * 2 + sizeIndicator) * correctScroll-0.75, -1)
```
in sliding_indicator.dart it looks perfect. (I am using 20 as inActiveindicator size and 21 as activeIndicator size)

**Comment by NikitaAmelinCR** [comment]
Hi @FRANIAZA! In new version we have fix this issue. Now it should be alright.
