### ISSUE TITLE
Can't scroll on web

### ISSUE THREAD

**Issue by marcio-pessoa** [Cleveroad/flutter_sliding_tutorial#9]
Hi dear.

The sliding is not work on web build.

Ideally I believe it could have forward and backward buttons for web interface.

**Comment by NikitaAmelinCR** [comment]
Hi @marcio-pessoa! Sorry for delay. These buttons were added in #11. Please, update version in your pubspeck.

**Comment by marcio-pessoa** [comment]
I'm going to test.

Thanks a lot.

**Comment by marcio-pessoa** [comment]
Hi @NikitaAmelinCR .

Sorry for delay, I was out of office, but today I updated to the new version. All tests OK.

Thank you!
